---
title: "dataProcessing"
author: "Fares Burwag"
date: "23/06/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(pheatmap)
library(ggrepel)
library(iq)
library(limma)
library(preprocessCore)
library(UpSetR)
library(RColorBrewer)

```


Only run the chunk below if you do not have the reportParsedIqQuant.tsv file generated. It takes a while to run...

```{r reading in TSV and processing IQ at 0.01 threshold}
##########################################################################################
##first we can filter and parse the report data into a better format for IQ
raw = read_tsv('reportFiles/report.tsv', show_col_types = FALSE) %>%
  dplyr::mutate(File.Name = sub('^.*_fares(.*)_dia_.*\\.raw', '\\1', File.Name,ignore.case = T)) %>%
  dplyr::filter(Q.Value <= 0.01)

##save the data
write.table(raw, 'reportFiles/reportParsed.tsv', 
            col.names = TRUE, row.names = FALSE, quote = FALSE, sep = '\t')


##run the IQ analysis
iqResult = process_long_format('reportFiles/reportParsed.tsv', 
                           output_filename = 'reportFiles/medNorm_reportParsedIqQuant.tsv',
                           annotation_col = 'Genes',
                           normalization = 'median',
                           filter_double_less = c("Q.Value" = "0.01", "PG.Q.Value" = "0.01"),
                           peptide_extractor = function(x) gsub("[0-9].*$", "", x))
##parse the IQ result
proData = read_tsv('reportFiles/reportParsedIqQuant.tsv', show_col_types = FALSE) %>%
  dplyr::rename(accession = 'Protein.Group',
                symbol = 'Genes')
proData_norm = read_tsv('reportFiles/medNorm_reportParsedIqQuant.tsv', show_col_types = FALSE) %>%
  dplyr::rename(accession = 'Protein.Group',
                symbol = 'Genes')


##save the data
saveRDS(proData,file = "reportFiles/parsedRDSFile.rds")
write.table(proData, "reportFiles/processedRDS.rds.tsv",
            col.names = TRUE, row.names = FALSE, quote = FALSE, sep = '\t')
saveRDS(proData_norm,file = "reportFiles/medNorm_parsedRDSFile.rds")
write.table(proData_norm, "reportFiles/medNorm_processedRDS.rds.tsv",
            col.names = TRUE, row.names = FALSE, quote = FALSE, sep = '\t')

```

Begin running code from here

```{r }

proData_norm <- read_tsv("medNorm_reportParsedIqQuant.tsv")

## Filtering for peptides with two or more detected peptides
proData_clean <- proData_norm %>%
  filter(n_peptides >= 2)
temp <- proData_clean

## Counts of non-NA values (n >= 2)
temp[,5:ncol(temp)] <- temp[,sort(colnames(temp[5:ncol(temp)]))]
temp <- temp[5:ncol(temp)] %>%
  map_df(function(x) sum(!is.na(x))) %>%
  t() %>% as.data.frame() %>%
  dplyr::rename(protein_count = V1) %>%
  rownames_to_column("sample") %>%
  mutate(category = case_when(grepl("Surf", sample, ignore.case = T) ~ "Surfaceome",
    grepl("Total|Whole", sample, ignore.case = T) ~ "Whole Proteome",
    TRUE ~ NA),
    sample_type = case_when(grepl("Medullo", sample, ignore.case = T) ~ "Medulloblastoma",
    TRUE ~ "Normal Tissue"),
    sample_id = str_match(sample, "_(.*)$")[,2])

ggplot(temp, aes(x = sample_id, y = protein_count, fill = category))+
  geom_col(stat = "identity",position = "dodge")+
  coord_flip()+
  geom_hline(yintercept = median(temp$protein_count), linetype = "dashed", color = "red")


```

```{r}
### Boxplot distribution per sample for all detected proteins
boxplot.matrix(as.matrix(proData_norm[,5:ncol(proData_norm)]))
### Boxplot distribution per sample for all proteins with >= 2 detected peptides
boxplot.matrix(as.matrix(proData_clean[,5:ncol(proData_clean)]))

```


```{r PCA with non-imputed Data}

## Collect numeric columns
temp <- proData_clean
pcaData <- temp[,5:ncol(temp)] %>%
  as.data.frame()
row.names(pcaData) <- temp$accession

## Run PrComp - any rows with NA values will be omitted from calculating principle components.
pcaOutput_noImp <- prcomp(~., data = pcaData, scale = TRUE, center = TRUE, na.action = na.omit)

## Getting PCA output
temp_df <- as.data.frame(pcaOutput_noImp$rotation)
temp_df["sample"] <- row.names(temp_df)

## Visualizaing distribution of samples using first and second PC. Note that a large
## majority of variability in data is captured by the first component (check the barplot below)
temp_df <- temp_df %>%
  mutate(sample_type = case_when(grepl("surf", sample, ignore.case = T) ~ "Surfaceome",
                                 grepl("(whole)|(total)", sample, ignore.case = T) ~ "WholeProteome"),
         sample_category = case_when(grepl("medullo", sample, ignore.case = T) ~ "Medullo",
                                    grepl("(cerebel)|(frontal)", sample, ignore.case = T) ~ "Normal Cerebellum",
                                    TRUE ~ "Other"),
         sampleLabel = paste(sample_type, sample_category, sep = " - "))

pcaVis_noImp <- ggplot(temp_df, aes(x = PC1, y = PC2, color = sampleLabel))+
  geom_point() +
  geom_text_repel(data = temp_df[temp_df$sample_category == "Medullo",], 
                   aes(label = str_match(sample, "(GR|SHH)[0-9A-Z]*")[,1]),
                   size = 3,
                   force = 2)+
  scale_color_brewer(palette = "Dark2")

pcaVis_noImp
```

```{r}

replace_lowest_x <- function(x){
  replace(x, list = which(is.na(x)), values = sample(x[x <= quantile(x, 0.005, na.rm = T) & !is.na(x)], size = sum(is.na(x)),replace = T))
}

## Quick imputation using minProb
temp <- proData_clean
temp[,5:ncol(temp)] <- apply(temp[,5:ncol(temp)], 2, function(x) replace_lowest_x(x))

pcaData <- temp[,5:ncol(temp)] %>%
  as.data.frame()
row.names(pcaData) <- temp$accession
pcaOutput_minProbImp <- prcomp(~., data = pcaData, scale = TRUE, center = TRUE, na.action = na.omit)


temp_df <- as.data.frame(pcaOutput_minProbImp$rotation)
temp_df["sample"] <- row.names(temp_df)

temp_df <- temp_df %>%
  mutate(sample_type = case_when(grepl("surf", sample, ignore.case = T) ~ "Surfaceome",
                                 grepl("(whole)|(total)", sample, ignore.case = T) ~ "WholeProteome"),
         sample_category = case_when(grepl("medullo", sample, ignore.case = T) ~ "Medullo",
                                    grepl("(cerebel)|(frontal)", sample, ignore.case = T) ~ "Normal Cerebellum",
                                    TRUE ~ "Other"),
         sampleLabel = paste(sample_type, sample_category, sep = " - "))

pcaVis_withImp <- ggplot(temp_df, aes(x = PC1, y = PC2, color = sampleLabel))+
  geom_point() +
  geom_text_repel(data = temp_df[temp_df$sample_category == "Medullo",], 
                   aes(label = str_match(sample, "(GR|SHH)[0-9A-Z]*")[,1]),
                   size = 3,
                   force = 2)+
  scale_color_brewer(palette = "Dark2")

pcaVis_withImp

```

```{r distribution of eigenvalues for PCAs}

## Distribution of eigenvalues prior to imputation
barplot((pcaOutput_noImp$sdev)^2)
## Distribution of eigen values following imputation
barplot((pcaOutput_minProbImp$sdev)^2)

```

```{r LIMMA without imputation}

## Filtering proteins with less than 2 detected peptides
temp <- proData_norm %>% filter(n_peptides >= 2)

## Selecting columns of interest (Surfaceome + Normal|GR3|GR4|SHH samples)
fullnormalSurf_data <- temp[,grepl("normalsurf", colnames(temp), ignore.case = T)]
fullmedulloSurfGR3_data <- temp[,grepl("Surf.*GR3", colnames(temp))]
fullmedulloSurfGR4_data <- temp[,grepl("Surf.*GR4", colnames(temp))]
fullmedulloSurfSHH_data <- temp[,grepl("Surf.*SHH", colnames(temp))]

## Combining the above four vectors in the given order.
combinedLimma_data <- as.matrix(cbind(fullnormalSurf_data, fullmedulloSurfGR3_data,
                                      fullmedulloSurfGR4_data,fullmedulloSurfSHH_data))
## The above line applies quantile normalization - feel free to add/remove.

## Distribution of intensities without any protein normalization  
boxplot.matrix(as.matrix(combinedLimma_data))

## Designating the sample categories - all healthy tissue samples are classified as 'normal'
design_categories <- c(rep("normal",12), rep("GR3",4), rep("GR4",3), rep("SHH",2))
design <- model.matrix(~ 0 + design_categories)
colnames(design) <- gsub("design_categories", "", colnames(design))

## Setting up contrasts for LIMMA
categories <- c("GR3", "GR4", "SHH", "normal")
category_contrasts <- c()
category_contrasts <- combn(categories, 2) %>% apply(2, function(x){
  append(category_contrasts, paste0(x[[1]], "-", x[[2]]))
})
limmaContrasts <- makeContrasts(contrasts = category_contrasts, levels = design)
limmaMatrix <- combinedLimma_data %>% as.matrix()
row.names(limmaMatrix) <- temp$accession

## Fitting model
limmaFit <- lmFit(limmaMatrix, design) %>%
  contrasts.fit(limmaContrasts) %>%
  eBayes()

## Group 3 results relative to normal
hits_group3 <- topTable(limmaFit, coef = "GR3-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_group3['subtype'] <- "Group3"
## Group 4 results relative to normal
hits_group4 <- topTable(limmaFit, coef = "GR4-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_group4['subtype'] <- "Group4"
## SHH results relative to normal
hits_SHH <- topTable(limmaFit, coef = "SHH-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_SHH['subtype'] <- "SHH"
## Combining all results with a subtype column
hits_combined <- rbind(hits_group3, hits_group4, hits_SHH)

```


```{r UpSet plot for LIMMA without imputation}

## UpSet visualization of all LIMMA hits that have an adj.Pval <= 0.05
UpSetR_input <- UpSetR::fromList(list(`Group3` = hits_group3$symbol[hits_group3$adj.P.Val <= 0.05],
                      `Group4` = hits_group4$symbol[hits_group4$adj.P.Val <= 0.05],
                      `SHH` = hits_SHH$symbol[hits_SHH$adj.P.Val <= 0.05]))

upset(UpSetR_input, order.by = "freq", )

```


```{r Volcano plot without imputation}
adjP_threshold <- 0.05
logFC_threshold <- 1

sigProteins_all <- hits_group3 %>%
  filter(adj.P.Val <= 0.05, abs(logFC) >= logFC_threshold)

sigProteins_up <- hits_group3 %>%
  filter(adj.P.Val <=  adjP_threshold, logFC >= logFC_threshold) %>%
  head(10)

sigProteins_down <- hits_group3 %>%
  filter(adj.P.Val <=  adjP_threshold, logFC <= -logFC_threshold) %>%
  head(10)

ggplot(hits_group3, aes(x = logFC, y = -log10(adj.P.Val)))+
  geom_point(color = "#6b6b6b", alpha = 0.1)+
  geom_point(data = sigProteins_all, color = "black")+
  geom_point(data = sigProteins_down, color = "blue")+
  geom_point(data = sigProteins_up, color = "red")+
  geom_vline(xintercept = +logFC_threshold, color = "#808080")+
  geom_vline(xintercept = -logFC_threshold, color = "#808080")+
  geom_hline(yintercept = -log10(adjP_threshold), color = "#808080")+
  geom_label_repel(data = sigProteins_down, aes(label = symbol),
                   vjust = 0.5,
                   nudge_x = -4,
                   nudge_y = +0.5,
                   max.overlaps = Inf,
                   size = 3.5,
                   force = 6,
                   segment.size = 0.2,
                   direction = "y")+
  coord_cartesian(ylim = c(0, 5), xlim = c(-10, 10))+
  geom_label_repel(data = sigProteins_up, aes(label = symbol),
                   vjust = 0.5,
                   nudge_x = 5,
                   nudge_y = 0,
                   max.overlaps = Inf,
                   size = 3.5,
                   force = 6,
                   segment.size = 0.2,
                   direction = "y")+
  coord_cartesian(ylim = c(0, 8.5), xlim = c(-10, 10))+
  labs(x = "Log2FC [Group3-Healthy]", y = "Adjusted p-value")
  
```



```{r LIMMA with imputation and filtering}
set.seed(123)

## MinProb imputation code
replace_lowest_x <- function(x){
  replace(x, list = which(is.na(x)), values = sample(x[x <= quantile(x, 0.005, na.rm = T) & !is.na(x)], size = sum(is.na(x)),replace = T))
}

## Filtering for n >= 2 peptides
temp <- proData_clean

## Filtering for proteins that have data for at least 4 medullo samples
temp_filtered <- temp[temp[,grepl("medullo.*surf.*GR3", colnames(temp), ignore.case = T)] %>% apply(1, function(x)sum(!is.na(x)) >= 3),]
## The idea behind the above step is to limit genes to those where at least 3 medullo
## samples have measured data. This limits the effects of imputed data 

## Selecting Medullo + Normal surfaceome samples
normalSurf_data <- temp_filtered[,grepl("normalsurf", colnames(temp_filtered), ignore.case = T)]
medulloSurfGR3_data <- temp_filtered[,grepl("Surf.*GR3", colnames(temp_filtered))]
medulloSurfGR4_data <- temp_filtered[,grepl("Surf.*GR4", colnames(temp_filtered))]
medulloSurfSHH_data <- temp_filtered[,grepl("Surf.*SHH", colnames(temp_filtered))]
combinedLimma_data <- as.matrix(cbind(normalSurf_data, medulloSurfGR3_data,
                                      medulloSurfGR4_data,medulloSurfSHH_data))

## Data distribution before imputation and normalization 
boxplot.matrix(as.matrix(combinedLimma_data))
## Quantile normalization
combinedLimmaImp_data <- normalize.quantiles(combinedLimma_data)
## Distribution after imputation
# boxplot.matrix(as.matrix(combinedLimmaImp_data))
## Applying log2 transformation and imputation
combinedLimmaImp_data <- apply(log2(combinedLimmaImp_data), 2, function(x) replace_lowest_x(x))
## Distribution after imputation and normalization
boxplot.matrix(as.matrix(combinedLimmaImp_data))
# boxplot.matrix(log2(as.matrix(combinedLimmaImp_data)))

design_categories <- c(rep("normal",12), rep("GR3",4), rep("GR4",3), rep("SHH",2))
design <- model.matrix(~ 0 + design_categories)
colnames(design) <- gsub("design_categories", "", colnames(design))

categories <- c("GR3", "GR4", "SHH", "normal")
category_contrasts <- c()
category_contrasts <- combn(categories, 2) %>% apply(2, function(x){
  append(category_contrasts, paste0(x[[1]], "-", x[[2]]))
})

limmaContrasts <- makeContrasts(contrasts = category_contrasts, levels = design)
limmaMatrix_imp <- (combinedLimmaImp_data %>% as.matrix())
row.names(limmaMatrix_imp) <- temp_filtered$accession

## Fitting LIMMA model
limmaFit_imp <- lmFit(limmaMatrix_imp, design) %>%
  contrasts.fit(limmaContrasts) %>%
  eBayes()

## Group3 results
hits_group3_imp <- topTable(limmaFit_imp, coef = "GR3-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_group3_imp['subtype'] <- "Group3"
## Group4 results
hits_group4_imp <- topTable(limmaFit_imp, coef = "GR4-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_group4_imp['subtype'] <- "Group4"
## SHH results
hits_SHH_imp <- topTable(limmaFit_imp, coef = "SHH-normal",number = 20000) %>%
  merge(proData_norm[,1:2], by.x = "row.names", by.y = "accession") %>%
  arrange(adj.P.Val)
hits_SHH_imp['subtype'] <- "SHH"
## All results
hits_combined_imp <- rbind(hits_group3_imp, hits_group4_imp, hits_SHH_imp)

```


```{r UpSetplot with imputation}
## UpSet plot of hits
UpSetR_input_imp <- UpSetR::fromList(list(`Group3` = hits_group3_imp$symbol[hits_group3_imp$adj.P.Val <= 0.05 & hits_group3_imp$logFC > 0],
                      `Group4` = hits_group4$symbol[hits_group4_imp$adj.P.Val <= 0.05 & hits_group4_imp$logFC > 0],
                      `SHH` = hits_SHH$symbol[hits_SHH_imp$adj.P.Val <= 0.05 & hits_SHH_imp$logFC > 0]))

upset(UpSetR_input_imp, order.by = "freq", text.scale = 1.3)

```


```{r volcano plot with imputation}
adjP_threshold <- 0.05
logFC_threshold <- 0.25

sigProteins_all <- hits_group3_imp %>%
  filter(adj.P.Val <= 0.05, abs(logFC) >= logFC_threshold)

sigProteins_up <- hits_group3_imp %>%
  filter(adj.P.Val <=  adjP_threshold, logFC >= logFC_threshold) %>%
  head(10)

sigProteins_down <- hits_group3_imp %>%
  filter(adj.P.Val <=  adjP_threshold, logFC <= -logFC_threshold) %>%
  head(10)

ggplot(hits_group3_imp, aes(x = logFC, y = -log10(adj.P.Val)))+
  geom_point(color = "#6b6b6b", alpha = 0.1)+
  geom_point(data = sigProteins_all, color = "black")+
  geom_point(data = sigProteins_down, color = "blue")+
  geom_point(data = sigProteins_up, color = "red")+
  geom_vline(xintercept = +logFC_threshold, color = "#808080")+
  geom_vline(xintercept = -logFC_threshold, color = "#808080")+
  geom_hline(yintercept = -log10(adjP_threshold), color = "#808080")+
  geom_label_repel(data = sigProteins_down, aes(label = symbol),
                   vjust = 0.5,
                   nudge_x = -1,
                   nudge_y = +0.5,
                   max.overlaps = Inf,
                   size = 3.5,
                   force = 6,
                   segment.size = 0.2,
                   direction = "y")+
  coord_cartesian(ylim = c(0, 5), xlim = c(-10, 10))+
  geom_label_repel(data = sigProteins_up, aes(label = symbol),
                   vjust = 0.5,
                   nudge_x = 1,
                   nudge_y = 0,
                   max.overlaps = Inf,
                   size = 3.5,
                   force = 2,
                   segment.size = 0.2,
                   direction = "y")+
  coord_cartesian(ylim = c(0, 10), xlim = c(-2, 2))+
  labs(x = "Log2FC [Group3-Healthy]", y = "-log10 Adjusted P-value")
  
```




```{r Validating hits}
## A few housekeeping genes to check - PPIA, GAPDH, PGK1, RPL13A, SDHA, etc...
gene_of_interest <- "GAPDH"

temp <- cbind(fullnormalSurf_data, fullmedulloSurfGR3_data, fullmedulloSurfGR4_data, fullmedulloSurfSHH_data)
temp["symbol"] <- proData_clean$symbol

temp_df <- temp %>% dplyr::filter(symbol == gene_of_interest) %>%
  dplyr::select(-22) %>% t() %>% as.data.frame()
temp_df["tissue_category"] <- c(str_match(row.names(temp_df)[1:12], "_(cerebellum|[A-Za-z]*)")[,2],
                                rep("Group3", 4), rep("Group4", 3), rep("SHH", 2))
borplot_df <- temp_df %>%
  group_by(tissue_category) %>%
  summarize(mean_expression = mean(V1, na.rm = T))

ggplot(borplot_df, aes(x = reorder(tissue_category, mean_expression), y = mean_expression))+
  geom_bar(stat = "identity", color = "black", fill = "#86DDE5")+
  geom_point(data = temp_df, aes(x = tissue_category, y = V1))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_cartesian(ylim = c(8,22))+
  labs(y = paste0("Relative expression of ",gene_of_interest), x = "Tissue")

```



```{r Export RDS object with upregulated hits}

saveRDS(hits_combined_imp[hits_combined_imp$logFC >= 0,], "exportFiles_CSV/allHits_withImpwith2xNorm.rds")


```





