---
title: "Surfaceome Dependency Analysis"
author: "Fares Burwag"
date: "15/08/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ReactomePA)
library(fgsea)
library(ggrepel)
library(RColorBrewer)
```



```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072*2)

## DepMap CRISPR dependency probability scores from DepMap Public 23Q2
depMapDependency_data <- read_csv("CERES/CRISPRGeneDependency.csv")
colnames(depMapDependency_data) <- str_match(colnames(depMapDependency_data), "[A-Z0-9a-z]*")

## DepMap CRISPR dependency effect scores from DepMap Public 23Q2
depMapEffect_data <- read_csv("CERES/CRISPRGeneEffect.csv")
colnames(depMapEffect_data) <- str_match(colnames(depMapEffect_data), "[A-Z0-9a-z]*")
depMapEffect_data <- depMapEffect_data %>% rename(`...1` = "ModelID")

## DepMap RNAi effect scores (with DEMETER algorithm) from DEMETER V6
depMapDEMETER_data <- read_csv("CERES/D2_combined_gene_dep_scores.csv") %>%
  dplyr::filter(!grepl("\\&",`...1`)) %>%
  dplyr::mutate(`...1` = str_match(`...1`, "^([A-Za-z0-9]*)")[,2]) %>%
  dplyr::group_by(`...1`) %>%
  dplyr::slice(1) %>%
  dplyr::rename(symbol = `...1`) %>%
  column_to_rownames("symbol")
colnames(depMapDEMETER_data) <- str_match(colnames(depMapDEMETER_data),"^([A-Za-z0-9\\-]*)_.*")[,2]
depMapDEMETER_data <- depMapDEMETER_data %>% t() %>% as.data.frame() %>%
  rownames_to_column("Model") %>%
  mutate(Model = gsub("-", "", Model)) %>%
  mutate(Model = gsub(" ", "", Model)) %>%
  mutate(Model = toupper(Model)) %>%
  as.tibble()

## DepMap Public Expression data from Public 23Q2
depMapExpPublic_data <- read_csv("Expression_Public_23Q2.csv")

## Model metadata for CRISPR and RNAi Projects.
depMapCLmeta <- read_csv("CERES/Model.csv") %>%
  dplyr::mutate(StrippedCellLineName = toupper(StrippedCellLineName))
depMapDEMETERmeta <- read_csv("CERES/ModelDEMETER.csv") %>%
  mutate(compatibleCLN = str_match(CCLE_ID,"^([A-Za-z0-9\\-]*)_.*")[,2]) %>%
  mutate(compatibleCLN = gsub("-", "", compatibleCLN)) %>%
  mutate(compatibleCLN = toupper(compatibleCLN)) %>%
  as.tibble()
```


```{r Tidy - CRISPR Dependency Probability}

# Tidying CRISPR Dependency Data
depAllHits <- readRDS("exportFiles_CSV/allHits_withImpwith2xNorm.rds")
depSigGr3Hits <- depAllHits[depAllHits$subtype == "Group3" & depAllHits$adj.P.Val <= 0.05,]
relevant_genes <- depSigGr3Hits$symbol[depSigGr3Hits$symbol %in% colnames(depMapDependency_data)]

depMapDependencyRel_data <- depMapDependency_data[,1] %>%
  merge(depMapCLmeta[,c(1,3,11,22,23,24)], by.x = "ModelID", by.y = "ModelID", all.x = TRUE)
depMapDependencyRel_data <- cbind(depMapDependencyRel_data, depMapDependency_data[,relevant_genes])

depMapDependencyRelLong_data <- depMapDependencyRel_data %>%
  pivot_longer(7:ncol(depMapDependencyRel_data), names_to = "symbol", values_to = "dependency_probability")

```


```{r Tidy - CRISPR Dependency Effect Score}

## Tidying CRISPR Effect Data Table
relevant_genes <- depSigGr3Hits$symbol[depSigGr3Hits$symbol %in% colnames(depMapEffect_data)]

depMapEffectRel_data <- depMapEffect_data[,1] %>%
  merge(depMapCLmeta[,c(1,3,4,11,22,23,24)], by.x = "ModelID", by.y = "ModelID", all.x = TRUE)
depMapEffectRel_data <- cbind(depMapEffectRel_data, depMapEffect_data[,relevant_genes])

depMapEffectRelLong_data <- depMapEffectRel_data %>%
  pivot_longer(8:ncol(depMapEffectRel_data), names_to = "symbol", values_to = "gene_effect")

depMap_Effect_medullo <- depMapEffectRelLong_data %>%
  filter(OncotreeSubtype == "Medulloblastoma") %>%
  group_by(symbol, OncotreeLineage, OncotreeSubtype, StrippedCellLineName) %>%
  filter(StrippedCellLineName %in% c("D283MED", "D341MED", "D425", "D458"))
### Group 3 MB CellLines => D283 (GR3/4), D341, D425, D458 (the rest are SHH)

```



```{r Tidy - RNAi DEMETER Dependency Scores}

## Tidying RNAi Dependency Scores Data Table [DEMETER]
relevant_genes <- depSigGr3Hits$symbol[depSigGr3Hits$symbol %in% colnames(depMapDEMETER_data)]

depMapDEMETERRel_data <- depMapDEMETER_data[,1] %>%
  merge(depMapCLmeta[,c(1,3,4,11,22,23,24)], by.x = "Model", by.y = "StrippedCellLineName", all.x = TRUE)
depMapDEMETERRel_data <- cbind(depMapDEMETERRel_data, depMapDEMETER_data[,relevant_genes])

depMapDEMETERRelLong_data <- depMapDEMETERRel_data %>%
  pivot_longer(8:ncol(depMapDEMETERRel_data), names_to = "symbol", values_to = "gene_effect")

depMap_DEMETER_medullo <- depMapDEMETERRelLong_data %>%
  filter(OncotreeSubtype == "Medulloblastoma") %>%
  filter(Model %in% c("D283MED", "D341MED", "D425", "D458"))
### Group 3 MB CellLines => D283 (GR3/4), D341, D425, D458 (the rest are SHH)

```

```{r Correlating RNAi and CRISPR Dependency Effect Scores}

# RNAi DEMETER and CRISPR correlation
temp <- depMapDEMETERRelLong_data %>%
  merge(depMapEffectRelLong_data[,c(1,8,9)], by = c("ModelID", "symbol"), suffix = c("_DEMETER","_CRISPR"))

## Correlation statistics for gene effect scores (DEMETER vs. CRISPR)
temp_stat <- cor.test(temp$gene_effect_DEMETER, temp$gene_effect_CRISPR)

## Scatter plot
ggplot(temp %>% filter(OncotreeSubtype == "Medulloblastoma"), aes(x = gene_effect_CRISPR, y = gene_effect_DEMETER))+
  geom_point(size = 0.5)+
  geom_vline(xintercept = -0.5, linetype = "dashed")+
  geom_hline(yintercept = -0.5, linetype = "dashed")+
  geom_smooth(method = "lm", se = FALSE)+
  annotate(geom = "rect", xmin = -0.5, xmax = Inf, ymin = -0.5, ymax = -Inf, fill = "red", alpha = 0.1)+
  annotate(geom = "label", x = -0.3, y = -1.5, label = paste0("R = ", round(temp_stat$estimate,3),"\nP-val = ", temp_stat$p.value), hjust = 0)

## Based on the distribution, purely using RNAi scores would sigificantly reduce identified
## dependent genes. DepMap recommends CRISPRi as a more sensitive tool for detecting dependent
## genes within a cell line. As a result, I'll use RNAi as an additional metric when scoring hits.

```


```{r DepMap Scatter - Minimum CRISPR Score against Cell Line Dependency Percentage}

## Try graphing percentage of cell lines in CRISPR database that are dependent on gene (X-axis) and
## minimum (most negative) effect score of gene dependence in Gr3 MB

depMapSummary_percent <- depMapDependencyRelLong_data %>%
  group_by(symbol, over50 = dependency_probability >= 0.5) %>%
  summarize(count = n()) %>%
  mutate(percent_cellLines = count/sum(count) * 100) %>%
  filter(over50 == TRUE)

depMapSummary_percent <- depMapSummary_percent %>%
  merge(depMap_Effect_medullo %>% group_by(symbol) %>% arrange(gene_effect) %>% dplyr::slice(1), by = "symbol")

## Labelled genes
depMapSummary_essentialMedullo_1 <- depMapSummary_percent %>%
  filter(gene_effect <= -0.5, percent_cellLines <= 10)

depMapSummary_essentialMedullo_2 <- depMapSummary_percent %>%
  filter(gene_effect <= -0.5, percent_cellLines >= 90)

ggplot(depMapSummary_percent, aes(x = percent_cellLines, y = -gene_effect))+
  geom_point(size = 1.5, aes(shape = StrippedCellLineName))+
  geom_vline(xintercept = 10, linetype = "dashed")+
  geom_vline(xintercept = 90, linetype = "dashed")+
  labs(x = "Percentage of cell lines dependent on gene (DepProb < 0.5)",
       y = "- Median Gene effect score")+
  annotate(geom = "rect", xmin = 0, xmax = 10, ymin = 0.5, ymax = Inf, fill = "green", alpha = 0.15)+
  annotate(geom = "rect", xmin = 90, xmax = 100, ymin = 0.5, ymax = Inf, fill = "green", alpha = 0.15)+
  geom_hline(yintercept = 0.5)+
  geom_label_repel(aes(label = symbol), data = depMapSummary_essentialMedullo_1, max.overlaps = Inf,
             force = 5,
             nudge_x = 20,
             nudge_y = 1.5,
             vjust = 0.5,
             hjust = 0.5,
             direction = "y",
             segment.size = 0.3)+
  geom_label_repel(aes(label = symbol), data = depMapSummary_essentialMedullo_2, max.overlaps = Inf,
             force = 10,
             nudge_x = -30,
             nudge_y = 1,
             vjust = 0.5,
             hjust = 0.5,
             # direction = "y",
             segment.size = 0.3)+
  scale_color_brewer(palette = "Dark2")

## Area highlighted in green are:
## - left are hits that are likely specific to medulloblastoma relative to other cell lines
## - right are hits that are broadly targetable across many cancer cell lines including Gr3MB
  
```


```{r DepMap Barplot - Proportion of 4 Cell Lines Dependent}

### Things left to do:
### Score targets based on the number of cell lines out of 4 that they fulfill 'dependency' criteria.
depMap_Effect_medullo["is_dependent"] <- depMap_Effect_medullo$gene_effect <= -0.4
depMap_rankedHits_data <- depMap_Effect_medullo %>%
  group_by(symbol, is_dependent) %>%
  summarize(count = n()) %>%
  dplyr::filter(is_dependent == TRUE) %>%
  mutate(propCellLine_dependent = count/4) %>%
  dplyr::select(-count, -is_dependent)
  
depMap_meanEffect_medullo <- depMap_Effect_medullo %>%
  group_by(symbol) %>%
  summarize(mean_effect = mean(gene_effect))

depMap_rankedHits_data <- merge(depMap_rankedHits_data, depMap_meanEffect_medullo, all = TRUE)
depMap_rankedHits_data$propCellLine_dependent <- replace(depMap_rankedHits_data$propCellLine_dependent,
                                              which(is.na(depMap_rankedHits_data$propCellLine_dependent)),
                                              0)
depMap_rankedHits_data <- depMap_rankedHits_data %>%
  arrange(propCellLine_dependent,mean_effect)
ggplot(depMap_rankedHits_data %>% filter(propCellLine_dependent > 0), aes(y = -mean_effect))+
  geom_col(aes(x = reorder(symbol, propCellLine_dependent), y = propCellLine_dependent), fill = "#86DDE5", color = "black")+
  geom_point(aes(x = reorder(symbol, propCellLine_dependent), y = -mean_effect/2), color = "#7F7F7F", size = 3)+
  scale_y_continuous(sec.axis = sec_axis(~.*2, name="- Mean Effect Score"),breaks = c(0,0.25,0.5, 0.75,1))+
  labs(y = "Proportion of MED-group3 cell lines dependent", x = "Target gene")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```



```{r Relative Effect Score of Gene to All Genes per Cell Line}

gene_of_interest <- "IMPG2"

## Plot showing distribution of 4 cell line dependency effect scores relative to other cancers by lineage
ggplot(depMapEffectRelLong_data %>% filter(symbol == gene_of_interest), aes(x = OncotreeLineage, y = gene_effect))+
  geom_boxplot()+
  geom_point(data = depMap_Effect_medullo %>% filter(symbol == gene_of_interest),
             aes(y = gene_effect, color = OncotreeSubtype))+
  coord_flip()

## Plot of dependency effect of gene of interest relative to all genes in 4 cell lines.
ggplot(depMap_Effect_medullo, aes(x = StrippedCellLineName, y  = gene_effect))+
  geom_jitter(color = "grey")+
  geom_boxplot(outlier.shape = NA)+
  geom_point(data = depMap_Effect_medullo %>% filter(symbol == gene_of_interest), aes(color = symbol))+
  labs(color = "Median dependency")

```


```{r}

## Combining data for export for final scoring
depCombinedMetrics_data <- depMap_Effect_medullo[,-10] %>%
  merge(depMap_DEMETER_medullo[,c(2,8,9)], 
        all.x = TRUE, 
        suffix = c("CRISPR", "DEMETER"), 
        by = c("ModelID","symbol")) %>%
  merge(depMap_rankedHits_data[,-3], by = "symbol")
  

## Export all medulloblastoma dependency data for score calculations
saveRDS(depCombinedMetrics_data,"exportFiles_CSV/medulloDepMapRanking.rds")

```

```{r}

```

